import type { PresetId, ProjectState } from "../types";

export const defaultDebugSettings: ProjectState["debug"] = {
  substrateMode: "none",
  maskBounds: false,
  glyphOutlines: false,
  glyphBounds: false,
  baseline: false,
  glyphOrigins: false,
  markOrigins: false,
  emitter: false,
  waveField: false,
  markCount: true,
  frameTime: false,
  costEstimate: false,
};

export const baseState: ProjectState = {
  version: 4,
  text: "SUBSTRATE",
  fontSize: 148,
  tracking: -3,
  renderer: "flow",
  seed: 24091,
  density: 46,
  amplitude: 22,
  frequency: 18,
  turbulence: 42,
  edgeInfluence: 68,
  exportMode: "artwork",
  exportFrameMode: "current",
  precision: 1,
  maxNodes: 2800,
  substrateQuality: "medium",
  preset: "Edge Current",
  emitter: {
    id: "emitter-1",
    glyphId: null,
    enabled: false,
    sourceMode: "counter-center",
    fieldType: "radial-wave",
    amplitude: 1,
    frequency: 0.09,
    phase: 0,
    radius: 430,
    falloff: "smoothstep",
    selfInfluence: 1,
    neighborInfluence: 0.65,
    blendMode: "add",
    customX: 600,
    customY: 360,
  },
  waveContourMode: "continuous",
  waveDotSpacing: 11,
  waveDotRadius: 1.8,
  diffuserDomain: "text-halo",
  diffuserComposition: "behind-text",
  diffuserDotRadius: 2.2,
  diffuserRingContrast: 0.72,
  diffuserHaloPadding: 80,
  glyphFieldMode: "off",
  glyphFieldInfluence: 60,
  glyphFieldDisplacement: 12,
  glyphFieldDensity: 45,
  glyphFieldRadius: 45,
  glyphFieldOpacity: 20,
  debug: defaultDebugSettings,
  font: null,
};

export const presets: Record<Exclude<PresetId, "Custom">, Partial<ProjectState>> = {
  "Edge Current": { renderer: "flow", density: 46, amplitude: 22, frequency: 18, turbulence: 42, edgeInfluence: 68 },
  "Sonic Ripple": { renderer: "ripple", density: 34, amplitude: 32, frequency: 12, turbulence: 14, edgeInfluence: 82 },
  "Signal Dust": { renderer: "dots", density: 58, amplitude: 12, frequency: 26, turbulence: 66, edgeInfluence: 52 },
  "SDF Current": { renderer: "sdf-flow", density: 52, amplitude: 18, turbulence: 24, edgeInfluence: 78, maxNodes: 2400 },
  "Contour Thread": { renderer: "sdf-streamlines", density: 42, amplitude: 30, turbulence: 18, edgeInfluence: 72, maxNodes: 3200 },
  "Topographic Type": { renderer: "sdf-contours", density: 58, amplitude: 34, turbulence: 6, edgeInfluence: 38, maxNodes: 4000 },
  "Halftone Press": { renderer: "sdf-halftone", density: 62, amplitude: 26, turbulence: 22, edgeInfluence: 44, maxNodes: 3000 },
  "Glyph Ripple": {
    renderer: "wave-contours",
    density: 48,
    amplitude: 28,
    frequency: 18,
    edgeInfluence: 45,
    maxNodes: 4000,
    waveContourMode: "continuous",
    emitter: { ...baseState.emitter, enabled: true, neighborInfluence: 0.62 },
  },
  "Dotted Diffuser": {
    renderer: "wave-contours",
    density: 56,
    amplitude: 30,
    frequency: 21,
    edgeInfluence: 55,
    maxNodes: 3600,
    waveContourMode: "dotted",
    waveDotSpacing: 10,
    waveDotRadius: 1.7,
    emitter: { ...baseState.emitter, enabled: true, neighborInfluence: 0.88, falloff: "gaussian" },
  },
  "Sonic Halftone": {
    renderer: "sdf-halftone", density: 64, amplitude: 27, turbulence: 16, edgeInfluence: 38, maxNodes: 3400,
    glyphFieldMode: "strong", glyphFieldInfluence: 86, glyphFieldDisplacement: 18, glyphFieldDensity: 72, glyphFieldRadius: 68,
    emitter: { ...baseState.emitter, enabled: true, glyphId: "auto-o-middle", radius: 430, neighborInfluence: 1.15 },
  },
  "Sonic Contours": {
    renderer: "sdf-contours", density: 60, amplitude: 32, turbulence: 4, edgeInfluence: 34, maxNodes: 4300,
    glyphFieldMode: "strong", glyphFieldInfluence: 78, glyphFieldDisplacement: 16,
    emitter: { ...baseState.emitter, enabled: true, glyphId: "auto-o-middle", radius: 440, neighborInfluence: 1.1 },
  },
  "Sonic Stream": {
    renderer: "sdf-streamlines", density: 48, amplitude: 30, turbulence: 8, edgeInfluence: 62, maxNodes: 3800,
    glyphFieldMode: "strong", glyphFieldInfluence: 76, glyphFieldDisplacement: 14, glyphFieldDensity: 38,
    emitter: { ...baseState.emitter, enabled: true, glyphId: "auto-o-middle", radius: 450, neighborInfluence: 1.05 },
  },
  "Sonic Diffuser": {
    renderer: "glyph-diffuser",
    density: 54,
    amplitude: 26,
    frequency: 20,
    turbulence: 28,
    edgeInfluence: 72,
    maxNodes: 3200,
    diffuserDomain: "text-halo",
    diffuserComposition: "behind-text",
    diffuserDotRadius: 2,
    diffuserRingContrast: 0.78,
    diffuserHaloPadding: 90,
    emitter: { ...baseState.emitter, enabled: true, glyphId: "auto-o-middle", radius: 390, neighborInfluence: 0.9, falloff: "gaussian" },
  },
};

export const presetIds = [...Object.keys(presets), "Custom"] as PresetId[];

export function applyPreset(state: ProjectState, preset: PresetId): ProjectState {
  if (preset === "Custom") return { ...state, preset };
  return { ...state, ...presets[preset], preset };
}
