import type { PresetId, ProjectState } from "../types";

export const defaultDebugSettings: ProjectState["debug"] = {
  substrateMode: "none",
  maskBounds: false,
  glyphOutlines: false,
  glyphBounds: false,
  baseline: false,
  glyphOrigins: false,
  markOrigins: false,
  emitter: false,
  waveField: false,
  markCount: true,
  frameTime: false,
  costEstimate: false,
};

export const baseState: ProjectState = {
  version: 5,
  text: "SUBSTRATE",
  fontSize: 148,
  tracking: -3,
  renderer: "flow",
  seed: 24091,
  density: 46,
  amplitude: 22,
  frequency: 18,
  turbulence: 42,
  edgeInfluence: 68,
  exportMode: "artwork",
  exportFrameMode: "current",
  precision: 1,
  maxNodes: 2800,
  substrateQuality: "medium",
  preset: "Edge Current",
  emitter: {
    id: "emitter-1",
    glyphId: null,
    enabled: false,
    sourceMode: "counter-center",
    fieldType: "radial-wave",
    amplitude: 1,
    frequency: 0.09,
    phase: 0,
    radius: 430,
    falloff: "smoothstep",
    selfInfluence: 1,
    neighborInfluence: 0.65,
    blendMode: "add",
    customX: 600,
    customY: 360,
  },
  emitterMode: "single",
  emitters: [{ id: "emitter-1", glyphId: null, enabled: true, weight: 1, phaseOffset: 0, radiusMultiplier: 1, label: "Emitter 1" }],
  fieldBlendMode: "add",
  waveContourMode: "continuous",
  waveDotSpacing: 11,
  waveDotRadius: 1.8,
  diffuserDomain: "text-halo",
  diffuserComposition: "behind-text",
  diffuserDotRadius: 2.2,
  diffuserRingContrast: 0.72,
  ringSharpness: 2.4,
  bandWidth: 0.28,
  diffuserHaloPadding: 80,
  textOverlayOpacity: 1,
  edgeErosionAmount: 0.2,
  edgeErosionWidth: 16,
  interiorProtection: 0.68,
  overlayMode: "solid",
  outlineStrokeWidth: 1.5,
  outlineWarpAmount: 8,
  outlineWarpScale: 1,
  outlineWarpSmoothing: 0.65,
  outlineWarpEdgeBias: 0.35,
  outlineWarpMaxDisplacement: 18,
  preserveCounters: true,
  glyphFieldMode: "off",
  glyphFieldInfluence: 60,
  glyphFieldDisplacement: 12,
  glyphFieldDensity: 45,
  glyphFieldRadius: 45,
  glyphFieldOpacity: 20,
  debug: defaultDebugSettings,
  font: null,
};

export const presets: Record<Exclude<PresetId, "Custom">, Partial<ProjectState>> = {
  "Edge Current": { renderer: "flow", density: 46, amplitude: 22, frequency: 18, turbulence: 42, edgeInfluence: 68 },
  "Sonic Ripple": { renderer: "ripple", density: 34, amplitude: 32, frequency: 12, turbulence: 14, edgeInfluence: 82 },
  "Signal Dust": { renderer: "dots", density: 58, amplitude: 12, frequency: 26, turbulence: 66, edgeInfluence: 52 },
  "SDF Current": { renderer: "sdf-flow", density: 52, amplitude: 18, turbulence: 24, edgeInfluence: 78, maxNodes: 2400 },
  "Contour Thread": { renderer: "sdf-streamlines", density: 42, amplitude: 30, turbulence: 18, edgeInfluence: 72, maxNodes: 3200 },
  "Topographic Type": { renderer: "sdf-contours", density: 58, amplitude: 34, turbulence: 6, edgeInfluence: 38, maxNodes: 4000 },
  "Halftone Press": { renderer: "sdf-halftone", density: 62, amplitude: 26, turbulence: 22, edgeInfluence: 44, maxNodes: 3000 },
  "Glyph Ripple": {
    renderer: "wave-contours",
    density: 48,
    amplitude: 28,
    frequency: 18,
    edgeInfluence: 45,
    maxNodes: 4000,
    waveContourMode: "continuous",
    emitter: { ...baseState.emitter, enabled: true, neighborInfluence: 0.62 },
  },
  "Dotted Diffuser": {
    renderer: "wave-contours",
    density: 56,
    amplitude: 30,
    frequency: 21,
    edgeInfluence: 55,
    maxNodes: 3600,
    waveContourMode: "dotted",
    waveDotSpacing: 10,
    waveDotRadius: 1.7,
    emitter: { ...baseState.emitter, enabled: true, neighborInfluence: 0.88, falloff: "gaussian" },
  },
  "Sonic Halftone": {
    renderer: "sdf-halftone", density: 70, amplitude: 22, turbulence: 11, edgeInfluence: 46, maxNodes: 3600,
    glyphFieldMode: "strong", glyphFieldInfluence: 92, glyphFieldDisplacement: 22, glyphFieldDensity: 86, glyphFieldRadius: 58,
    ringSharpness: 2.8, bandWidth: 0.34,
    emitter: { ...baseState.emitter, enabled: true, glyphId: "auto-o-middle", radius: 410, neighborInfluence: 0.82 },
  },
  "Sonic Contours": {
    renderer: "sdf-contours", density: 56, amplitude: 28, turbulence: 3, edgeInfluence: 40, maxNodes: 4300,
    glyphFieldMode: "strong", glyphFieldInfluence: 72, glyphFieldDisplacement: 11,
    emitter: { ...baseState.emitter, enabled: true, glyphId: "auto-o-middle", radius: 430, neighborInfluence: 0.78 },
  },
  "Sonic Stream": {
    renderer: "sdf-streamlines", density: 46, amplitude: 27, turbulence: 5, edgeInfluence: 64, maxNodes: 3800,
    glyphFieldMode: "subtle", glyphFieldInfluence: 68, glyphFieldDisplacement: 9, glyphFieldDensity: 32,
    emitter: { ...baseState.emitter, enabled: true, glyphId: "auto-o-middle", radius: 440, neighborInfluence: 0.72 },
  },
  "Sonic Diffuser": {
    renderer: "glyph-diffuser",
    density: 68,
    amplitude: 26,
    frequency: 20,
    turbulence: 16,
    edgeInfluence: 72,
    maxNodes: 3200,
    diffuserDomain: "text-halo",
    diffuserComposition: "edge-eroded",
    diffuserDotRadius: 1.45,
    diffuserRingContrast: 0.94,
    ringSharpness: 3.2,
    bandWidth: 0.24,
    diffuserHaloPadding: 70,
    textOverlayOpacity: 1,
    edgeErosionAmount: 0.24,
    edgeErosionWidth: 18,
    interiorProtection: 0.66,
    overlayMode: "solid",
    emitter: { ...baseState.emitter, enabled: true, glyphId: "auto-o-middle", radius: 370, neighborInfluence: 0.68, falloff: "gaussian" },
  },
  "Sonic Warp": {
    renderer: "glyph-diffuser",
    density: 60,
    amplitude: 28,
    frequency: 18,
    turbulence: 12,
    edgeInfluence: 70,
    maxNodes: 3400,
    diffuserDomain: "text-halo",
    diffuserComposition: "edge-eroded",
    diffuserDotRadius: 1.35,
    diffuserRingContrast: 0.92,
    ringSharpness: 3,
    bandWidth: 0.26,
    diffuserHaloPadding: 70,
    textOverlayOpacity: 1,
    edgeErosionAmount: 0.12,
    edgeErosionWidth: 16,
    interiorProtection: 0.72,
    overlayMode: "warped-outline",
    outlineWarpAmount: 19,
    outlineWarpScale: 1.05,
    outlineWarpSmoothing: 0.8,
    outlineWarpEdgeBias: 0.24,
    outlineWarpMaxDisplacement: 26,
    preserveCounters: true,
    emitter: { ...baseState.emitter, enabled: true, glyphId: "auto-o-middle", radius: 410, neighborInfluence: 0.74, falloff: "gaussian" },
  },
  "Sonic Interference": {
    renderer: "glyph-diffuser",
    density: 62,
    amplitude: 28,
    frequency: 19,
    turbulence: 14,
    edgeInfluence: 68,
    maxNodes: 3600,
    diffuserDomain: "text-halo",
    diffuserComposition: "behind-text",
    diffuserDotRadius: 1.5,
    diffuserRingContrast: 0.88,
    ringSharpness: 2.8,
    bandWidth: 0.28,
    diffuserHaloPadding: 60,
    textOverlayOpacity: 1,
    overlayMode: "solid",
    emitterMode: "multiple",
    fieldBlendMode: "add",
    emitters: [
      { id: "se-1", glyphId: "auto-o-middle", enabled: true, weight: 1, phaseOffset: 0, radiusMultiplier: 1, label: "O / mid" },
      { id: "se-2", glyphId: "auto-first", enabled: true, weight: 0.68, phaseOffset: Math.PI, radiusMultiplier: 0.82, label: "First" },
      { id: "se-3", glyphId: "auto-last", enabled: true, weight: 0.56, phaseOffset: Math.PI * 0.5, radiusMultiplier: 0.72, label: "Last" },
    ],
    emitter: { ...baseState.emitter, enabled: true, radius: 390, neighborInfluence: 0.72, falloff: "gaussian" },
  },
  "Counter Resonance": {
    renderer: "glyph-diffuser",
    density: 58,
    amplitude: 26,
    frequency: 21,
    turbulence: 10,
    edgeInfluence: 62,
    maxNodes: 3200,
    diffuserDomain: "text-halo",
    diffuserComposition: "behind-text",
    diffuserDotRadius: 1.6,
    diffuserRingContrast: 0.84,
    ringSharpness: 2.6,
    bandWidth: 0.3,
    diffuserHaloPadding: 50,
    textOverlayOpacity: 1,
    overlayMode: "solid",
    emitterMode: "multiple",
    fieldBlendMode: "add",
    emitters: [
      { id: "cr-1", glyphId: "auto-o-middle", enabled: true, weight: 1, phaseOffset: 0, radiusMultiplier: 0.9, label: "Counter O" },
      { id: "cr-2", glyphId: "auto-o-middle", enabled: true, weight: 0.62, phaseOffset: Math.PI, radiusMultiplier: 0.68, label: "Counter O²" },
    ],
    emitter: { ...baseState.emitter, enabled: true, radius: 360, neighborInfluence: 0.68, selfInfluence: 0.9, falloff: "gaussian" },
  },
};

export const presetIds = [...Object.keys(presets), "Custom"] as PresetId[];

export function applyPreset(state: ProjectState, preset: PresetId): ProjectState {
  if (preset === "Custom") return { ...state, preset };
  return { ...state, ...presets[preset], preset };
}
